version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: msbuild /t:Restore /v:m

build:
  verbosity: minimal

artifacts:
- path: src/ModSink.WPF/bin/Release/net461
  name: binaries

deploy:
- provider: GitHub
  auth_token:
    secure: TLChfAMJcjhyw7dQ6WNllA/sc420Hq4fk9V9/VUD1kFOm4ZJpfiBlwaqdVRPbQeP
  artifact: binaries
  prerelease: true
  on:
    branch: master
