version: '{build}'
image: Visual Studio 2017
build_script:
- ps: ./build.ps1
test: off
artifacts:
  - path: 'out\nuget\**\*'
    name: NugetPackages
environment:
  NUGET_KEY:
    secure: Ob5EBMb27Otq2AJxXRNMa/2ziJQ3fqQuy9gjg8fCk2/MtaX09owlCfYAXHDnW6DB
